### PR TITLE
feat: implemented an error 500 page

### PR DESCRIPTION
**Pull request by thetabyte**
This pull request contains the implementation for an error 500 page which basically describes an internal server error and contains a link that takes users back to the homepage. Please find attached a screenshot of the page and a hostel link 

intServErr500

### CODE REVIEW

**Comment by tomiwaajayi** [comment]
Please where is the hosted link

**Comment by thetabyte** [comment]
I am sorry i was in a rush

Please this is the hosted link

https://fmlerror500.netlify.app/

**Comment by tomiwaajayi** [comment]
Chief please change the image.
The image quality won't fly

**Comment by thetabyte** [comment]
Please when you say change the image do you mean i should change its format?
I saved it in JPG. Should i change it to PNG?

**Comment by thetabyte** [comment]
Hello chief, I have made adjustments by changing the image. Please have a look-see and let me know if it is better. 
Below is the new hosted link reflecting the new update

https://fmlerror500.netlify.app/


Here is the new image i used

2newerr500

Here is how it looks on the hosted link below



intServErr500-1
intServerr500-2
intServerr500-3

**Pull request merged**
