### PR TITLE
Issue #18

### PR DESCRIPTION
**Pull request by ronnycrown**
[FML Login](https://mystifying-mccarthy-0df7fd.netlify.app/src/login)

Screenshot_20200629-132601

### CODE REVIEW

**Comment by tomiwaajayi** [comment]
Please host your work and attach a link to it here @ronnycrown

**Comment by ronnycrown** [comment]
I already did that,  but here's it again.

https://mystifying-mccarthy-0df7fd.netlify.app/src/login

**Comment by Babsmutini** [comment]
@tomiwaajayi

**Comment by tomiwaajayi** [comment]
@Babsmutini 
She will make a new pr.
She is just expected to validate the forms that the other guys made.

**Pull request closed without merging**
