### PR TITLE
#feat: fundmylaptpblog

### PR DESCRIPTION
**Pull request by kennyOlakunle**

### CODE REVIEW

**Comment by tomiwaajayi** [comment]
Host and provide a link please

**Comment by kennyOlakunle** [comment]
[**Please Click to check Live Link**](https://kennyolakunle.github.io/)

**Comment by tomiwaajayi** [comment]
Screenshot 2020-07-02 at 12 12 03 PM
Please make sure that your PR is not touching any file...or deleting anything from another html file

**Comment by kennyOlakunle** [comment]
@tomiwaajayi I double-checked again, It's not conflicting or has changed any file.

**Comment by kennyOlakunle** [comment]
@tomiwaajayi I double-checked again, It's not conflicting or has changed any file. I also made sure I pulled the updated file from the repo before I made this pull request

**Comment by tomiwaajayi** [comment]
Doesn't conform the FML Style !

**Pull request closed without merging**
