### PR TITLE
Login page

### PR DESCRIPTION
**Pull request by shina1**
Here is a link to the live preview: https://fund-my-laptop-fe-login-page.shina1.vercel.app/login.html

### CODE REVIEW

**Comment by tomiwaajayi** [comment]
@shina1 you have conflicting files.
Pull first before you push

**Comment by shina1** [comment]
conflict resolved.
please verify.

**Comment by Babsmutini** [comment]
@tomiwaajayi

**Comment by tomiwaajayi** [comment]
Your work doesn't conform to what Is required.
It has been reassigned.

**Comment by shina1** [comment]
noted

**Pull request closed without merging**
