### PR TITLE
success modal

### PR DESCRIPTION
**Pull request by femithz**
Success Modal Implemented

### CODE REVIEW

**Comment by Babsmutini** [comment]
Please host your file and provide a live link

**Comment by femithz** [comment]
https://quizzical-raman-b25046.netlify.app/src/payment-success-modal

**Comment by Babsmutini** [comment]
@femithz please change your pr title to the right format

**Comment by tomiwaajayi** [comment]
Screenshot 2020-07-01 at 10 12 44 AM

Please look at the payment page on the design and implement it properly

**Comment by femithz** [comment]
can I have access to the Figma editable access so as to copy the property for each text, thinks that would make things better, then about my PR title.

**Comment by tomiwaajayi** [comment]
@femithz Export it to your own draft

**Pull request closed without merging**
