### PR TITLE
fixed bug ... with @lyndaar

### PR DESCRIPTION
**Pull request by onifs10**

### CODE REVIEW

**Comment by onifs10** [comment]
hosted link is in deploy preview 
Screenshot from 2020-06-29 13-05-47

**Comment by tomiwaajayi** [comment]
@onifs10  please I need to see the hosted link.

**Comment by onifs10** [comment]
https://fml-sample.netlify.app/src/policy.html
@tomiwaajayi

**Comment by tomiwaajayi** [comment]
Awesome stuff @onifs10

**Comment by onifs10** [comment]
Screenshot from 2020-06-29 15-23-42

**Pull request merged**
