### PR TITLE
Issue #37

### PR DESCRIPTION
**Pull request by amakaUche**
my contribution to fund my laptop FAQ dark mode page

### CODE REVIEW

**Comment by Babsmutini** [comment]
Live link Please

**Comment by tomiwaajayi** [comment]
@amakaUche Please live link

**Comment by tomiwaajayi** [comment]
Put your css in the custom-css folder

**Comment by amakaUche** [comment]
I have put my css in the custom css folder. Thanks

**Comment by tomiwaajayi** [comment]
Please attach a live link

**Comment by amakaUche** [comment]
https://sulaimon23.github.io/lapi/

image

**Comment by amakaUche** [comment]
Done

**Pull request closed without merging**
