### PR TITLE
Uloma Profile Set Up 2 

### LINKED ISSUE #183: Profile Setup form 2

### PR DESCRIPTION
**Pull request by ulomau**
My live link 

https://profilesetup.netlify.app/src/profilesetup2.html

figma design screenshoot 
Frame 1

my design screenshoot 
screencapture-profilesetup-netlify-app-src-profilesetup2-html-2020-07-10-21_48_27

### CODE REVIEW

**Comment by Babsmutini** [comment]
@ulomau  Please look at your design and try to replicate it. There is a lot of differences.
Right from alignments, margins. etc

**Comment by Babsmutini** [comment]
Please resolve your conflicts

**Comment by Babsmutini** [comment]
@ulomau

**Comment by Babsmutini** [comment]
@ulomau PLease resolve your conflicts

**Comment by simeon4real** [comment]
Please rename the files appropriately. File names like `uloma.css`.

**Pull request merged**
