### PR TITLE
Fml gallery

### PR DESCRIPTION
**Pull request by Reehah**

### CODE REVIEW

**Comment by tomiwaajayi** [comment]
You need to provide me a live link !

**Comment by Reehah** [comment]
https://hopeful-spence-e2354d.netlify.app/

That's it. Please check it out for necessary corrections

**Comment by Reehah** [comment]
https://serene-banach-6d2052.netlify.app/

**Comment by Reehah** [comment]
https://serene-banach-6d2052.netlify.app/ . That's the hosted link. Please
check it out. Thank you

**Comment by Reehah** [comment]
Thank you

**Pull request merged**
