### PR TITLE
fix: navbar

### PR DESCRIPTION
**Pull request by victorakanmidu**
Fixed nav to be as it is on figma 
Preview link: https://hardcore-wing-e9060e.netlify.app/

Spanshot:

nav

### CODE REVIEW

**Comment by tomiwaajayi** [comment]
The responsive view doesn't show the navbar content

**Comment by victorakanmidu** [comment]
Okay let me fix that quickly

**Comment by victorakanmidu** [comment]
This has been fixed now

**Comment by victorakanmidu** [comment]
This has been fixed now

**Pull request closed without merging**
