### PR TITLE
fml-blog-page

### PR DESCRIPTION
**Pull request by Reehah**
FML-BLOG PAGE

### CODE REVIEW

**Comment by tomiwaajayi** [comment]
@Reehah rename your files please

**Comment by Reehah** [comment]
I have renamed it.

**Comment by Reehah** [comment]
I have renamed the files already

**Comment by Reehah** [comment]
Kindly review

**Comment by tomiwaajayi** [comment]
Your PR is deleting a file from the Repo

**Comment by Reehah** [comment]
Please can you help me confirm which file. My system is currently dead. So
I'll fix it when there's light

**Comment by tomiwaajayi** [comment]
Screenshot 2020-07-01 at 10 13 50 PM
All the files that have red1

**Comment by Reehah** [comment]
Shit. That should be a mistake. How do I fix that problem

**Pull request closed without merging**
