### PR TITLE
feat: Verification 3

### LINKED ISSUE #181: Verification Form 3

### PR DESCRIPTION
**Pull request by Bobaddey**
hosted link: https://verification3.netlify.app
Figma link:https://www.figma.com/file/GTUbHki3xDCA4YWHrZ6gjl/Fund-My-Laptop-Project?node-id=0%3A1
slack username: @Bobaddey
screenshot: 
verif scrnsht

### CODE REVIEW

**Comment by Babsmutini** [comment]
@Bobaddey Your design is not responsive! 
The font-sizes of desktop and mobile view are suppose to be different.
It breaks totally on mobile.
Screen Shot 2020-07-09 at 12 46 53 AM

**Comment by Bobaddey** [comment]
@Babsmutini  I just fixed it... please check and merge

**Comment by Babsmutini** [comment]
@Bobaddey Your font sizes are not suppose to be the same on desktop and mobile.
PLease make changes to your li tags.
Try to replicate design

**Comment by Babsmutini** [comment]
@Bobaddey any changes yet?

**Comment by Bobaddey** [comment]
@Babsmutini Changes made... check and merge.
thanks

**Pull request merged**
