### PR TITLE
Fund my laptop payment page with mobile responsiveness 

### PR DESCRIPTION
**Pull request by babstunder**
Hosted Link
https://babstunder.github.io/payment-/

### CODE REVIEW

**Comment by babstunder** [comment]
Screenshot_20200702-145403

**Comment by tomiwaajayi** [comment]
Screenshot 2020-07-02 at 12 17 53 PM
Please fix your page responsiveness

**Comment by babstunder** [comment]
Fixed.... Thanks

**Comment by tomiwaajayi** [comment]
Screenshot 2020-07-02 at 4 39 23 PM
Please make sure that you're not touching someone else's work.
Look at that screenshot.

**Comment by babstunder** [comment]
Am  not changing 
It was the way I created the file

**Pull request closed without merging**
