### PR TITLE
landing-page-secion commit

### PR DESCRIPTION
**Pull request by Temially**

### CODE REVIEW

**Comment by tomiwaajayi** [comment]
host and provide a link please

**Comment by ChidiTeng** [comment]
https://landing-page-section.netlify.app/

**Comment by Temially** [comment]
> host and provide a link please

https://landing-page-section.netlify.app/

**Comment by tomiwaajayi** [comment]
please rename your html to landpage.html

**Comment by Temially** [comment]
> please rename your html to landpage.html

I've done that. Kindly check

**Comment by tomiwaajayi** [comment]
Check your file please
Your PR is deleting index.html if merged

**Comment by Temially** [comment]
> Check your file please
> Your PR is deleting index.html if merged

I renamed it to landpage.html as requested

**Comment by Temially** [comment]
> Check your file please
> Your PR is deleting index.html if merged

Please try to merge now. I've made some changes. Thanks

**Pull request closed without merging**
